@echo off
echo Starting OMS Server...
echo.
echo Checking Node.js installation...
node --version
echo.
echo Installing/Updating dependencies...
npm install
echo.
echo Starting server...
npm start
pause
