export const navigationMenus = {
  Super_Admin: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "Register HR Manager", path: "/hr-registration" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    //   {name: "HRattendance", path: "/hrAttendance"},
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "QuotationList", path: "/QuotationList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Admin: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "HR Registration", path: "/hr-registration" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
    { name: "Certificate", path: "/Certificate" },
    { name: "HrAttendance", path: "/HrAttendance" },
  ],
  // Subrole-specific navigation for Admin
  Admin_HR: [
    { name: "HR Dashboard", path: "/" },
    { name: "Employee Management", path: "/Db/employee" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "HR Registration", path: "/hr-registration" },
    { name: "Attendance", path: "/Attendance" },
    { name: "HrAttendance", path: "/HrAttendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "Recruitment", path: "/recruitment" },
    { name: "Certificate", path: "/Certificate" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Employee: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Intern: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
};
