export const navigationMenus = {
  Super_Admin: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "Register HR Manager", path: "/hr-registration" },
    { name: "Leave Management", path: "/super-admin-leave-management" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    //   {name: "HRattendance", path: "/hrAttendance"},
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "QuotationList", path: "/QuotationList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
    // Department Dashboards
    { name: "HR Dashboard", path: "/hr-dashboard" },
    { name: "IT Dashboard", path: "/it-dashboard" },
    { name: "Finance Dashboard", path: "/finance-dashboard" },
    { name: "Marketing Dashboard", path: "/marketing-dashboard" },
    { name: "Sales Dashboard", path: "/sales-dashboard" },
    { name: "Operations Dashboard", path: "/operations-dashboard" },
  ],
  Admin: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "HR Registration", path: "/hr-registration" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
    { name: "Certificate", path: "/Certificate" },
    { name: "HrAttendance", path: "/HrAttendance" },
    { name: "Apply Leave", path: "/hr-leave-application" },
    // Department Dashboards
    { name: "HR Dashboard", path: "/hr-dashboard" },
    { name: "IT Dashboard", path: "/it-dashboard" },
    { name: "Finance Dashboard", path: "/finance-dashboard" },
    { name: "Marketing Dashboard", path: "/marketing-dashboard" },
    { name: "Sales Dashboard", path: "/sales-dashboard" },
    { name: "Operations Dashboard", path: "/operations-dashboard" },
  ],
  // Subrole-specific navigation for Admin
  Admin_HR: [
    { name: "HR Dashboard", path: "/" },
    { name: "Employee Management", path: "/Db/employee" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "HR Registration", path: "/hr-registration" },
    { name: "Attendance", path: "/Attendance" },
    { name: "HrAttendance", path: "/HrAttendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "Recruitment", path: "/recruitment" },
    { name: "Certificate", path: "/Certificate" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Admin_Project_Manager: [
    { name: "Project Manager Dashboard", path: "/" },
    { name: "Project Management", path: "/project-management" },
    { name: "Team Management", path: "/team-management" },
    { name: "Task Tracking", path: "/task-tracking" },
    { name: "Time Management", path: "/time-management" },
    { name: "Resource Planning", path: "/resource-planning" },
    { name: "Client Communication", path: "/client-communication" },
    { name: "Reports & Analytics", path: "/reports-analytics" },
    { name: "Budget Management", path: "/budget-management" },
    { name: "Document Management", path: "/document-management" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Employee: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
  Intern: [
    { name: "Homepage", path: "/" },
    { name: "Db", path: "/Db" },
    { name: "Employee", path: "/Db/employee" },
    { name: "CandidateProfile", path: "/CandidateProfile" },
    { name: "Attendance", path: "/Attendance" },
    { name: "EmployeeAttendance", path: "/EmplyeAtendnc" },
    { name: "ProjectList", path: "/ProjectList" },
    { name: "chat", path: "/chat" },
    { name: "Inbox", path: "/Inbox" },
    { name: "SendEmail", path: "/Inbox/send-email" },
    { name: "EmailDetails", path: "/Inbox/email-details" },
    { name: "Calender", path: "/Calender" },
  ],
};
